service:
  name: authentication

plugins:
  - serverless-domain-manager

custom:
  domainNameMap:
    default: api.development.nevvi.net
    production: api.nevvi.net
  basePathMap:
    production: authentication
    development: authentication
    default: ${self:provider.stage}-authentication
  customDomain:
    domainName: ${self:custom.domainNameMap.${self:provider.stage}, self:custom.domainNameMap.default}
    basePath: ${self:custom.basePathMap.${self:provider.stage}, self:custom.basePathMap.default}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'test'}
  region: ${opt:region, 'us-east-1'}
  apiName: authentication-${self:provider.stage}
  stackName: authentication-${self:provider.stage}
  deploymentBucket:
    name: nevvi-serverless-deployment-bucket
  deploymentPrefix: ${self:provider.stage}

functions:
  test:
    handler: src/functions/Test.test
    events:
      - http:
          path: /
          method: get

  # Cognito Triggers
  preSignUpTrigger:
    handler: src/functions/CognitoTriggers.preSignUp